{{- if and .Values.persistence.exporter.enabled (not .Values.persistence.exporter.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "penpot.fullname" . }}-data-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "penpot.labels" . | nindent 4 }}
  {{- if .Values.persistence.exporter.annotations }}
  annotations:
    {{ toYaml .Values.persistence.exporter.annotations | indent 4 }}
  {{- end }}
spec:
  accessModes:
  {{- range .Values.persistence.exporter.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.exporter.size | quote }}
  {{- if .Values.persistence.exporter.storageClass }}
  storageClassName: "{{ .Values.persistence.exporter.storageClass }}"
  {{- end }}
{{- end -}}
